language: python

python:
  - 3.4
  - 3.5
  - 3.6

sudo: false

install:
  - pip install -r requirements.txt
  - pip install pytest


cache:
  directories:
    - $HOME/.cache/pip

script: ls && py.test --duration=10 .