language: python

python:
  - 3.4
  - 3.5
  - 3.6

sudo: false

install:
  - if [[ $TRAVIS_PYTHON_VERSION = "3.4" ]]; then pip install typing; fi
  - pip install -r requirements.txt
  - pip install pytest
  - pip install -e .

cache:
  directories:
    - $HOME/.cache/pip

script: py.test --duration=10 tests